Repository dataware-tools/manifests, pull requests merged in 2021-07, with the labels that each got.

#13 Fix the bug that demo-site does not work
  distributions/demo/kustomization.yaml
Labels: approved

#14 Fix the bug that users without permission `admin:user` fails to get metadata
  common/security/authorization-policy.yaml
Labels: approved, size/XS

#15 Persist demo site
  distributions/demo/kustomization.yaml
  distributions/demo/mounts.yaml
  distributions/demo/pvc.yaml
  distributions/demo/pydtk-v4.yaml
Labels: approved, size/M

#16 Bump api-meta-store to `v0.4.5`
  apps/api-meta-store/deployment.yaml
  apps/api-permission-manager/deployment.yaml
Labels: approved, size/XS

#17 Add webviz-related manifests
  apps/api-job-store/deployment.yaml
  contrib/webviz/gateway.yaml
  contrib/webviz/kustomization.yaml
  contrib/webviz/virtual-services.yaml
  distributions/demo/kustomization.yaml
Labels: approved, size/M

#18 Fix WEBVIZ_URL
  apps/api-job-store/deployment.yaml
Labels: approved

#19 Bump api-meta-store to `v0.4.6`
  apps/api-meta-store/deployment.yaml
Labels: approved, size/XS

#21 Fix AuthorizationPolicy
  common/security/authorization-policy.yaml
Labels: approved, size/S

#22 Bump api-meta-store to v0.4.7
  apps/api-meta-store/deployment.yaml
Labels: approved, size/M

#20 Bump up data-browser
  apps/app-data-browser-next/deployment.yaml
Labels: approved, size/XS
