Repository dataware-tools/manifests, pull requests merged in 2021-06, with the labels that each got.

#1 Bump api-file-provider
  apps/api-file-provider/deployment.yaml
Labels: approved, lgtm, size/XS

#2 Bump app-data-browser-next to master
  apps/app-data-browser-next/deployment.yaml
Labels: approved

#3 Bump app-user-manager to v0.1.0
  apps/app-user-manager/deployment.yaml
Labels: approved, size/XS

#4 Bump api-meta-store to v0.3.0
  apps/api-meta-store/deployment.yaml
Labels: approved, size/XS

#5 Bump app-launcher to v0.2.0
  apps/app-launcher/deployment.yaml
Labels: approved, size/XS

#6 Bump api-meta-store to v0.3.1
  apps/api-meta-store/deployment.yaml
Labels: approved, size/XS

#7 Add `require-auth0-user-admin`
  apps/api-permission-manager/deployment.yaml
  common/security/authorization-policy.yaml
Labels: approved, size/S

#8 Bump api-meta-store to `v0.3.2`
  apps/api-meta-store/deployment.yaml
Labels: approved

#9 Persist storage for DB of api-permission-manager
  apps/api-permission-manager/deployment.yaml
Labels: approved, size/S

#10 Bump api-meta-store to `v0.4.3`
  apps/api-meta-store/deployment.yaml
Labels: approved, size/XS

#11 Bump apps
  apps/app-data-browser-next/deployment.yaml
  apps/app-launcher/deployment.yaml
  apps/app-user-manager/deployment.yaml
  distributions/demo/auth0-client-configs.yaml
  distributions/demo/kustomization.yaml
Labels: approved, size/M
